### ISSUE TITLE
SAC seems to be underperforming

### ISSUE THREAD

**Issue by slerman12** [fabiopardo/tonic_data#2]
From looking at the benchmarks, SAC seems to be underperforming quite a bit. Have you seen this library's implementation? https://autonomous-learning-library.readthedocs.io/en/stable/index.html

**Comment by fabiopardo** [comment]
The Tonic agents could be better tuned for specific environments. For SAC I used the hyper parameters from Spinning Up in Deep RL and got comparable results to theirs. Those parameters where probably selected for the tasks shown in their benchmark (Gym MuJoCo tasks).
