### ISSUE TITLE
Are the saved benchmarks the best of 10 seeds or the average of 10 seeds? I noticed they have standard deviation shading around them, so is it average? In the readme it says best of.

### ISSUE THREAD

**Issue by slerman12** [fabiopardo/tonic_data#3]

**Comment by fabiopardo** [comment]
Hi! Each agent was trained with 10 seeds. The data originally logged in csv files produced during training were compressed in the pkl files. The plots show the average over the 10 seeds using solid lines and the interval between the best and worst seeds with the filled areas. A smoothing window of size 5 is also used. Those plots were generated using the plotting script provided on the main Tonic repository. Finally, the model weights (checkpoints) after 5M steps are also provided for each agent.
