### ISSUE TITLE
How to unpickle the log file?

### ISSUE THREAD

**Issue by sukritiverma1996** [fabiopardo/tonic_data#4]
Hi, I am having a lot of trouble getting to the data in the log.pkl files without knowing the structure of the pkl file itself. Could you share a code snippet showing how I can read this data?

**Comment by fabiopardo** [comment]
Hi! The CSV logs produced during training were combined as Pandas DataFrame and were serialized using zip compression. 
Therefore, the DataFrames can be restored using `pandas.read_pickle`.

For example to read the logs of the A2C agent on acrobot-swingup on 10 seeds, use:
```python
pandas.read_pickle('tonic_data/tensorflow/acrobot-swingup/A2C/log.pkl', compression='zip')
```
![image](https://user-images.githubusercontent.com/13062117/106389911-2fc50100-63e6-11eb-91c5-93987dcd4774.png)

For simpler logs (mostly performance) of all agents on all tasks you can also directly load the file provided in Tonic:
```python
pandas.read_pickle('tonic/data/logs/tensorflow_logs.pkl', compression='zip')
```
![image](https://user-images.githubusercontent.com/13062117/106390032-aeba3980-63e6-11eb-8a48-78c7332b09a0.png)

This last pkl file was intended to be as light as possible to remain in the main repository and be quickly loaded by the plotting script when comparing new results to baselines.
